name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      reg_rate:
        description: Regularization rate (C = 1/reg_rate)
        required: true
        default: "0.1"

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      AML_RG: cloud-shell-storage-eastus
      AML_WS: aml-ws

    steps:
      - name: Check out repo (latest main)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install/Update Azure ML CLI v2
        run: az extension add -n ml -y || az extension update -n ml

      - name: Validate job YAML
        run: |
          az ml job validate \
            --file src/job.yml \
            --resource-group "${{ env.AML_RG }}" \
            --workspace-name "${{ env.AML_WS }}"

      - name: Submit AML job
        run: |
          az ml job create \
            --file src/job.yml \
            --resource-group "${{ env.AML_RG }}" \
            --workspace-name "${{ env.AML_WS }}" \
            --set inputs.reg_rate=${{ inputs.reg_rate }}
