name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      reg_rate:
        description: Regularization rate (C = 1/reg_rate)
        required: true
        default: "0.1"

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      AML_RG: cloud-shell-storage-eastus
      AML_WS: aml-ws
      AML_ENV_IMAGE: mcr.microsoft.com/azureml/sklearn-0.24-ubuntu18.04-py37-cpu:latest

    steps:
      - name: Check out repo (latest main)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install/Update Azure ML CLI v2
        run: az extension add -n ml -y || az extension update -n ml
      
      - name: Verify RG and WS exist
        run: |
          az group show --name "${{ env.AML_RG }}" -o table
          az ml workspace show --name "${{ env.AML_WS }}" --resource-group "${{ env.AML_RG }}" -o table
          az ml compute show --name cpu-cluster --resource-group "${{ env.AML_RG }}" --workspace-name "${{ env.AML_WS }}" -o table

      - name: Validate job YAML
        run: |
          az ml job validate \
            --file src/job.yml \
            --resource-group "${{ env.AML_RG }}" \
            --workspace-name "${{ env.AML_WS }}"

      - name: Submit AML job (force safe environment + reg_rate)
        run: |
          az ml job create \
            --file src/job.yml \
            --resource-group "${{ env.AML_RG }}" \
            --workspace-name "${{ env.AML_WS }}" \
            --set environment.image="${{ env.AML_ENV_IMAGE }}" \
            --set inputs.reg_rate=${{ inputs.reg_rate }}
