name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      reg_rate:
        description: Regularization rate (C = 1/reg_rate)
        required: true
        default: "0.1"

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      AML_RG: cloud-shell-storage-eastus
      AML_WS: aml-ws

    steps:
      - name: Check out repo (latest main)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install/Update Azure ML CLI v2
        run: az extension add -n ml -y || az extension update -n ml

      - name: (Optional) Verify RG & WS
        run: |
          az group show --name "${{ env.AML_RG }}" -o table
          az ml workspace show --name "${{ env.AML_WS }}" --resource-group "${{ env.AML_RG }}" -o table
          
      - name: Validate AML job YAML
        run: |
          az ml job validate \
            --file src/job.yml \
            --resource-group "${{ env.AML_RG }}" \
            --workspace-name "${{ env.AML_WS }}"

      - name: Submit AML job
        shell: bash
        run: az ml job create --file src/job.yml --resource-group "${{ env.AML_RG }}" --workspace-name "${{ env.AML_WS }}" --set environment="azureml://registries/azureml/environments/AzureML-sklearn-0.24-ubuntu18.04-py37-cpu/versions/1" --set inputs.reg_rate=${{ inputs.reg_rate }}


